<h1>Details for <?php echo $model->getDisplayName(); ?></h1>

<p>
    <a href="<?php echo $this->url('spiffy_crud/details/create', array('name' => $name)); ?>">Create</a>
</p>

<?php echo $this->spiffycrud($name, $data); ?>

<p style="clear:left;">
    <a href="<?php echo $this->url('spiffy_crud'); ?>">Back to List</a>
</p>

<p>
    <a href="<?php echo $this->url('spiffy_crud/details/create', array('name' => $name)); ?>">Create</a>
</p>