<?php
/** @var \Zend\Form\Form $form */
$form->prepare();
$form->setAttribute('action', $url);
$form->setAttribute('method', 'post');

if (!$form->has('submit')) {
    $form->add(array(
        'name' => 'submit',
        'type' => 'submit',
        'attributes' => array(
            'value' => 'Submit'
        )
    ));
}
?>

<?php echo $this->form()->openTag($form) ?>
    <dl class="zend_form">
        <?php foreach ($form as $element): ?>
            <?php if (!$element instanceof \Zend\Form\Element\Submit): ?>
                <dt>
                    <?php echo $this->formLabel($element, $element->getAttribute('label') ? $element->getAttribute('label') : $element->getName()) ?>
                </dt>
            <?php endif ?>
            <dd><?php echo $this->formElement($element) . $this->formElementErrors($element) ?></dd>
        <?php endforeach ?>
    </dl>
<?php echo $this->form()->closeTag() ?>