<h1>Registered Models</h1>
<?php
/** @var \SpiffyCrud\CrudManager $manager */
echo '<ul>';
foreach ($manager->getCanonicalNames() as $realName => $canonicalName) {
    /** @var \SpiffyCrud\Model\ModelInterface $model */
    $model = $manager->get($canonicalName);
    printf(
        '<li><a href="%s">%s</a></li>',
        $this->url('spiffy_crud/details', array('name' => $canonicalName)),
        $realName
    );
}
echo '</ul>';