<?php foreach($this->models as $groupName => $models) : ?>
    <?php if ($groupName === \SpiffyCrud\CrudManager::UNGROUPED_NAME) continue; ?>
    <h2><?php echo $groupName;?></h2>
    <ul>
    <?php foreach ($models as $model) : ?>
        <li>
            <a href="<?php echo $this->url('spiffy_crud/details', array('name' => $model->getName()));?>">
                <?php echo $model->getName(); ?>
            </a>
        </li>
    <?php endforeach; ?>
    </ul>
<?php endforeach; ?>

<?php if (!empty($this->models[\SpiffyCrud\CrudManager::UNGROUPED_NAME])) : ?>
<h3>Remaining models</h3>
<ul>
<?php foreach($this->models[\SpiffyCrud\CrudManager::UNGROUPED_NAME] as $model) : ?>
    <li>
        <a href="<?php echo $this->url('spiffy_crud/details', array('name' => $model->getName()));?>">
            <?php echo $model->getName(); ?>
        </a>
    </li>
<?php endforeach; ?>
</ul>
<?php endif; ?>