<h1>Update</h1>

<?php
/** @var \Zend\Form\Form $form */
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register'));
$form->setAttribute('method', 'post');
?>

<?php echo $this->form()->openTag($form) ?>
<dl class="zend_form">
    <?php foreach ($form as $element): ?>
        <?php if (!$element instanceof Zend\Form\Element\Button): ?>
            <dt>
            <?php echo $this->formLabel($element, $element->getAttribute('label') ? $element->getAttribute('label') : $element->getName()) ?>
            </dt>
        <?php endif ?>
        <dd><?php echo $this->formElement($element) . $this->formElementErrors($element) ?></dd>
    <?php endforeach ?>
</dl>
<?php echo $this->form()->closeTag() ?>


<a href="<?php echo $this->url('spiffycrud'); ?>">Back to List</a>